name: Main action for deployment

on: 
  push:
    branches:
      - main

jobs: 
  call-reusable-workflow:
    runs-on: ubuntu-latest
    steps:
      # This step checks out a copy of the repository.
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - name: Build static files
        run: npm run build
      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v3.0.1
        with:
          path: SalFell.github.io/dist/
      - name: Deploy GitHub Pages site
        uses: actions/deploy-pages@v4.0.5
            
